### ISSUE TITLE
Validation fails after formatting

### ISSUE THREAD

**Issue by aliciapaz** [mihailpozarski/chilean-rutify#1]
**Describe the bug**
The validation fails after formatting a rut using the rutifier.

**To Reproduce**
Let's say you have a model with the following attributes: name, rut, commune. 

```
class Person < ApplicationRecord
  before_validation :format_rut, on: %i[create update]

  validates :name, presence: true
  validates :rut, presence: true, rut: true
  validates :commune, presence: true

  private

  def format_rut
    self.rut = Chilean::Rutify.format_rut(rut)
  end
end
```
Then I go to the console and type: 

```
p = Person.new(name: 'Bob, rut: '45235220', commune: 'Pica')
p.save! 
ActiveRecord::RecordInvalid: La validación falló: RUT is not a valid rut
p.rut
=> "4.523.522-0"
```

So the rut has been formatted correctly, but the validation fails for some reason. 

**Expected behavior**

A rut should be valid after is formatted.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox (doesn't really matter though)

**Additional context**
Thanks for this gem! It's a very useful module except for this weird behavior.

**Comment by mihailpozarski** [comment]
Hello Alicia! 

I think this issue comes from the rut verifier number, in your case "-0" is wrong and should be "-k" to be a real chilean rut, that's what the gem means for `not a valid rut`

The rules for having a valid rut are:
- The rut can contain only numbers from 0 to 9 and the letter K
- The rut must have a valid rut verifier digit based on the formula defined by Chile called "modulo 11"

you can check the formula on the gem [code here](https://github.com/mihailpozarski/chilean-rutify/blob/7cd936f439daf0cf17d74e0ef314af5751b8020f/lib/chilean/rutify.rb#L17)

also here is a [non so code explanation](https://es.wikipedia.org/wiki/Rol_%C3%9Anico_Tributario#:~:text=El%20formato%20del%20RUT%20es,XXX.&text=Tanto%20el%20RUT%20como%20el,determinada%2C%20sea%20natural%20o%20jur%C3%ADdica.)

**Comment by aliciapaz** [comment]
You're right! Thanks @mihailpozarski, that solves my issue.
